#!/bin/bash -ex
# publish assets to the lambda for public visibility

# the favicon is made with base64 tick.png > favicon.png64

# a pattern is to update, test, git commit/push, update
#pushd cv
if ! python -m py_compile *.py; then
  echo "not updating"    
  exit
else
  rm -rf __pycache__
fi

if ! python cv.py; then
  echo "not updating"
  exit
fi

# generate gitinfo so the git version is visible on site
git remote get-url origin > gitinfo.html
git log -1 --oneline >>gitinfo.html
date >> gitinfo.html
sed ':a;N;$!ba;s/\n/<br>/g' gitinfo.html > _gitinfo.html
mv _gitinfo.html gitinfo.html

# create zip file
if [ -e ../cv.zip ]; then
  rm ../cv.zip
fi

#pushd terraform
#terraform output -no-color > ../terraform_output.py
#popd

zip cv.zip *.py *.html *.png64 contents.html
#popd
# update lambda function
fn=cvdev
#fn=cv-experimental
aws lambda update-function-code --zip-file fileb://$PWD/cv.zip  --function-name $fn | grep CodeSize
echo aws logs tail /aws/lambda/$fn --follow
